### ISSUE TITLE
SCART Header, Male, Cable Type - Aliexpress link not working

### ISSUE THREAD

**Issue by stefanpausch** [jeffqchen/JeffParts#1]
The Aliexpress link to "SCART Header, Male, Cable Type" is not working anymore. Would you mind updating it. Thanks alot

**Comment by jeffqchen** [comment]
It looks like it's working now.

https://github.com/jeffqchen/JeffParts/blob/main/Connectors/SCART/Male%20Cable/info.md

**Comment by stefanpausch** [comment]
For me, it isn't :( 

Is this a location issue? - Would you mind sharing a screenshot of the item at Aliexpress? - Maybe then i am able to find the correct item there :)

![2023-02-28_08-52](https://user-images.githubusercontent.com/184467/221788625-dfa04273-87b7-4dbd-acdd-6b70b894ea22.png)

**Comment by jeffqchen** [comment]
![QQ20230228-032414](https://user-images.githubusercontent.com/25773768/221795677-e7b976f6-3dd9-45f4-adf9-a85de9a5dbd7.jpg)

**Comment by stefanpausch** [comment]
Thanks alot! - Looks like a location problem. - I am from germany, but i guess this is an EU wide issue. I think it has to do with the new EU packaging directive.

Same item, different store: https://www.aliexpress.com/item/1005004031337410.html
