### ISSUE TITLE
Female Connector

### ISSUE THREAD

**Issue by nsinav** [jeffqchen/JeffParts#3]
Hello. I am a little bit confused. What is the female conector to the back?

170-202-170L003
https://www.digikey.com/en/products/detail/norcomp-inc/170-202-170L003/1164238

OR

1599600
https://www.digikey.com/en/products/detail/phoenix-contact/1599600/3606927

Because the are a lot different.

Thanks.

**Comment by jeffqchen** [comment]
1599600 was confirmed to be compatible. And it's newer and cheaper.

**Comment by nsinav** [comment]
Thank you
